### PR TITLE
Added Delete, fixed a lot of bugs

### PR DESCRIPTION
**Pull request by karatemaccie**
Added tested delete methods and fixed a lot of bugs.

Tested!

Example code:
```java
/** Delete Server. **/
if (api.getServers().deleteServer(id)){ // If true, successful. If false, get the error.
	api.getDeleteMethods().getLastError(); //The error.
}

/** Delete User. **/
if (api.getUsers().deleteUser(id)){ // If true, successful. If false, get the error.
	api.getDeleteMethods().getLastError(); //The error.
}
	
/** Delete Node. **/
if (api.getNodes().deleteNode(id)){ // If true, successful. If false, get the error.
	api.getDeleteMethods().getLastError(); //The error.
}
```

### CODE REVIEW

**Comment by Doc94** [comment]
So sorry i forget upload any changes...
Change all POST of body plane text contend to JSON (The issue in panel say of only support for JSON request in POST)

**Comment by karatemaccie** [comment]
Sure, I'll merge them. Give me a few minutes

**Comment by karatemaccie** [comment]
Merged. No conflicts left.

**Comment by Doc94** [comment]
Ready, but need the .project file?

**Pull request merged**
